.phpsetup: &phpsetup
  cache:
    paths:
    - vendor/
  before_script:
  - bash ci/docker_install.sh > /dev/null
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install
  script:
  - php composer.phar run sniff-errors-only

test:7.2:
  image: php:7.2
  <<: *phpsetup
  include:
    - template: Dependency-Scanning.gitlab-ci.yml
    - template: SAST.gitlab-ci.yml
    