version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
        - ./docker/etc/nginx:/etc/nginx
        - ./docker/var/ssl:/var/ssl
        - .:/var/www/html
    ports:
        - "80:80"
        - "443:443"
  mysql:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: docker/php71-fpm.Dockerfile
    volumes:
      - .:/var/www/html
volumes:
  web:
  dbdata: