version: '2'

services:
  php73:
    build:
      context: .
      dockerfile: php73.Dockerfile
    volumes:
      - ../:/var/www
    command: php composer.phar start

  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    volumes:
      - ../:/var/www
    command: php composer.phar start

  php80:
    build:
      context: .
      dockerfile: php80.Dockerfile
    volumes:
      - ../:/var/www
    command: php composer.phar start
